const fs = require('fs');
const gettextParser = require("gettext-parser");
const localeFolder = './messages/';

const HEADER = `// Do not edit this file directly
export const messages = `;


var locales = {};
var completed = false;

let folders = fs.readdirSync(localeFolder);

folders.forEach(function (folder) {
    let shortcode = folder.substring(0, 2);
    locales[shortcode] = {};

    let messagePath = localeFolder + folder + "/LC_MESSAGES/";

    let domains = fs.readdirSync(messagePath).filter(fn => fn.endsWith('.po'));

    domains.forEach(function (file) {
        console.log("Reading " + messagePath + file);
        let texts = gettextParser.po.parse(fs.readFileSync(messagePath + file), "utf8");
        locales[shortcode][file.slice(0, -3)] = {};
        let translations = texts.translations[''];
        if (typeof translations == "undefined") {
            return;
        }
        Object.entries(translations).forEach(translation => {
            if (translation[1].msgid.length > 0) {
                locales[shortcode][file.slice(0, -3)][translation[1].msgid] = translation[1].msgstr[0];
            }
        });
    });
    //console.log("b", locales);
    completed = true;

});

let generated = "";
generated += HEADER;
generated += JSON.stringify(locales, null, 2);
generated += ";";

fs.writeFile('./messages.js', generated, function (err) {
    if (err) throw err;
    console.log('Wrote generated locales to messages.js');
});